### ISSUE TITLE
Inconsistency for default values in documentation

### ISSUE THREAD

**Issue by VDuchauffour** [econchick/interrogate#139]
### Description of the bug
It seems that documentation contains inconsistency about `ignore-init-method` and `ignore-nested-classes` in [configuration](https://interrogate.readthedocs.io/en/latest/#configuration) section and [command line options](https://interrogate.readthedocs.io/en/latest/#command-line-options). Command line options seems to match to default values [here](https://github.com/econchick/interrogate/blob/master/src/interrogate/config.py#L44) (i.e. set on `False`) while the configuration section indicates that they are set to `True` by default.
I guess if this error is correct, it is required to modify the README.rst file?
Thanks

**Comment by econchick** [comment]
Thanks! fixed
