### ISSUE TITLE
Don't require `toml` on Python 3.11

### ISSUE THREAD

**Issue by pawelad** [econchick/interrogate#150]
### Describe the feature you'd like
Hi!

I'm currently upgrading the Python version on of my projects to Python 3.11 (which added [tomllib](https://docs.python.org/3/library/tomllib.html) to the standard library) and was delighted to see that almost all packages I use dropped the requirement for `tomli`:

<img width="878" alt="Screenshot 2023-03-20 at 16 57 32" src="https://user-images.githubusercontent.com/7062874/226405276-4c0d0823-9aff-4c3d-ba3b-55f3c72f6fcd.png">

The only dependencies that don't use the the built in `tomllib` on Python 3.11 is `django-stubs` (https://github.com/typeddjango/django-stubs/issues/1408) and `interrogate`.

I'm not sure if there's a need to switch from `toml` to `tomli`, but ideally neither should be required on Python 3.11 and the built in `tomllib` should be used.

As far as I see, the replacement should be pretty straightforward and I'd be happy to provide a PR.

Lastly, an example of how `black` dealt with this:

https://github.com/psf/black/blob/ef6e079901d53a42dfae4ab10b081ce7a73a47b5/pyproject.toml#L71

https://github.com/psf/black/blob/ef6e079901d53a42dfae4ab10b081ce7a73a47b5/src/black/files.py#L26-L34

### Your Environment
- `interrogate` version(s) (`interrogate --version`: 1.5.0
- Operating System(s): macOS 12.6.3
- Python version(s): 3.11

**Comment by econchick** [comment]
Sorry for the silence! This is in master, and is queued for `1.7.0`, which I'm planning to release this month. I'll keep this open until I release :)

**Comment by econchick** [comment]
Released! feel free to re-open if this is still an issue.
