### ISSUE TITLE
Bug: Terminal width on Windows command is off by 1

### ISSUE THREAD

**Issue by ivarstange** [econchick/interrogate#20]
**Is this a BUG REPORT or FEATURE REQUEST?**:

* [x] bug
* [ ] feature

## Description of Bug or Feature
When generating the report, the last "|"-char for the table is on the next line, causing the output to look really weird. Expanding the windows command (terminal) width by 1 makes everything look nice again.

### Environment

- `interrogate` version(s): 1.1.4
- Operating System(s): Windows 10
- Python version(s): 3.7.6

I have not been able to check if it works with other versions of `interrogate`, OS or Python.

### What happened
Last "|" char in the table goes to the next line.

### What you expected to happen
Expect every output line to not be wrapped like this to the next line.

### How to reproduce it (as minimally and precisely as possible)
Open Windows Command and run interrogate to produce results.

### Anything else we need to know?
I've checked that this is not due to the output requiring this due to long outputs. There is plenty of available padding in each cell of the output.

Thank you for this awesome tool! :)

**Comment by econchick** [comment]
Hey @ivarstange - thanks so much for the bug! My apologies for the annoying issue - I'll take a look in the next couple of days.

**Comment by hectormz** [comment]
I noticed this too, but couldn't find the pattern. If I use Windows Terminal, it always correctly. And if I use any terminal inside VS Code, it's fine. But cmd/cmder/powershell on their own don't work. 

Let me know if I can help check things out on Windows.

**Comment by econchick** [comment]
@hectormz @ivarstange if either of you have a moment, would you mind trying out #23 to see if that addresses the issue you both are seeing?

**Comment by econchick** [comment]
@ivarstange @hectormz I released version `1.1.5` in hopes that I've fixed the off-by-1 issue. Please feel free to re-open this ticket if you still experience issues!
