### ISSUE TITLE
Flag for color coded output

### ISSUE THREAD

**Issue by ivarstange** [econchick/interrogate#25]
**Is this a BUG REPORT or FEATURE REQUEST?**:

* [ ] bug
* [X] feature

## Description of Bug or Feature
It would be really nice to get the output color-coded. Especially when `-vv` is flagged. In a reasonably large package in combination with a wide terminal output, correlating those "COVERED" and "MISSED" labels with the corresponding item is often difficult.

Having the option to print lines as green for covered items and red for missed items would be really great to quickly identify the items with no docstring.

**Comment by econchick** [comment]
great idea - should be easy enough; I'll try to incorporate it in the next release!

**Comment by econchick** [comment]
Added `--color` (default) / `--no-color` flags in `ddcfd464` and released in v 1.2.0 - thanks for the suggestion!
