### ISSUE TITLE
Feature Request: Flag to check pydocstyle

### ISSUE THREAD

**Issue by flamableconcrete** [econchick/interrogate#26]
**Is this a BUG REPORT or FEATURE REQUEST?**:

* [ ] bug
* [x] feature

## Description of Bug or Feature

I regularly use `flake8` and recently came across the `flake8-docstrings` extension which utilizes `pydocstyle` to check for various docstring content issues. It feels to me like `pydocstyle` is the kind of optional dependency/flag that could be incorporated here somehow. Possibly a third level of verbosity could look something like this?

```
$ interrogate -vvv [PATH]

==================== Coverage for /Users/lynn/dev/interrogate/ ======================
--------------------------------- Detailed Coverage ---------------------------------
| Name                                                                  |    Status |
|-----------------------------------------------------------------------|-----------|
| tests/unit/__init__.py (module)                                       |   COVERED |
|-----------------------------------------------------------------------|-----------|
| tests/unit/test_badge_gen.py (module)                                 |   COVERED |
|   test_save_badge (L14)                                               |   COVERED |
|     D201: No blank lines allowed before function docstring (found 1)  |   ------- |
|     D300: Use """triple double quotes""" (found '''-quotes)           |   ------- |
|   test_get_badge (L35)                                                |    MISSED |
|     D101: Docstring missing                                           |   ------- |
|   test_get_color (L44)                                                |   COVERED |
|   test_create (L61)                                                   |   COVERED |
|-----------------------------------------------------------------------|-----------|
```

Feel free to ignore/delete this issue if you aren't interested in going this direction. Great tool by the way though!

* pydocstyle: https://github.com/pycqa/pydocstyle
* Flake8 pydocstyle extension: https://pypi.org/project/flake8-docstrings/

**Comment by econchick** [comment]
Interesting idea! I'll take a look to see how much work it'd take to add this. Thanks!

**Comment by econchick** [comment]
Hey @flamableconcrete (apologies for the silence!) - I've given this some thought, and I'm choosing not to add this functionality. I want to keep this tool as simple as possible and just check doc coverage, not necessarily lint the docstrings themselves. Thank you v much for the idea though!

**Comment by flamableconcrete** [comment]
No worries - thanks for entertaining the thought!
