### ISSUE TITLE
Allow read configuration from 'setup.cfg' file

### ISSUE THREAD

**Issue by vyahello** [econchick/interrogate#35]
### Describe the feature you'd like
Currently, there is the only ability to read configuration from 'pyproject.toml' file. Please add this for 'setup.cfg' too.

### Your Environment
- Operating System(s): Mac OS, Linux
- Python version(s): python >=3.7

**Comment by econchick** [comment]
Sorry for the delayed response! This seems like a reasonable request! I'll look into it this week.

**Comment by econchick** [comment]
Hey @vyahello - I've added this with #44. I'll make a release later today (v1.3.0) with it included. Thanks for the suggestion!
