### ISSUE TITLE
Feature Request: ability to ignore property methods decorated with *@property*

### ISSUE THREAD

**Issue by jeremywitte** [econchick/interrogate#37]
### Describe the feature you'd like

I would like to be able to ignore class property methods that are defined with `@property` decorators. Many times these can be self-descriptive and do not follow the `get_` regex pattern.

### Your Environment

- `interrogate` version(s) (`interrogate --version`:
- Operating System(s):
- Python version(s):

### Additional context

I don't believe the existing `ignore-regex` option covers this use case but I could be wrong.

**Comment by econchick** [comment]
Thank you for the suggestion! That does make sense - I'll take a look into it sometime this week.

**Comment by econchick** [comment]
Hey @jeremywitte - I've (finally) added this in! It will be in v 1.3.0 (which should be released later today). Thanks again for the suggestion!
