### ISSUE TITLE
When Total=0 and Miss=0 I would expect the result to be SUCCESS rather than FAILED

### ISSUE THREAD

**Issue by JulienLajugie** [econchick/interrogate#50]
### Environment
python 3.7
interrogate 1.3.1

### Description of the bug
When nothing is missed but the coverage is 0 because there was nothing to document, I would expect the result to be SUCCESS.

- Summary -
| Name  | Total | Miss | Cover | Cover% |
|-------|-------|------|-------|--------|
|-------|-------|------|-------|--------|
| TOTAL |     0 |    0 |     0 |   0.0% |
- RESULT: FAILED (minimum: 60.0%, actual: 0.0%) -

### What you expected to happen
I would expect the result to be successful

### How to reproduce (as minimally and precisely as possible)
Create a module that do not contain any methods or properties. (In my case it was a module only defining type aliases.
Use this configuration:
[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = true
ignore-semiprivate = true
ignore-private = true
ignore-property-decorators = true
ignore-module = true
ignore-nested-functions = true
fail-under = 60
exclude = ["setup.py", "docs", "build", "test"]
verbose = 1
quiet = false
whitelist-regex = []
color = true

**Comment by econchick** [comment]
FYI the fix has been released in [1.3.2](https://pypi.org/project/interrogate/1.3.2/) - thanks!
