### ISSUE TITLE
[BUG] Exclude paths not os independent

### ISSUE THREAD

**Issue by s-weigand** [econchick/interrogate#51]
### Environment

- `interrogate` version(s) (`interrogate --version`: 1.3.1
- Operating System(s): Windows10
- Python version(s): 3.7.8

### Description of the bug
In one of my projects I exclude a subdir with autogenerated files, form being tested with `inrerrogate`.
In order for this to work crossplatform I need to define the exclusion twice.
Once with windows path separators `\\` and once with Posix separators `/`.
So I end up with the following config:
```toml
[tool.interrogate]
exclude = ["setup.py", "docs", "tests", ".eggs", "djangocms_equation\\migrations", "djangocms_equation/migrations"]
```

### What you expected to happen
Just using `"djangocms_equation/migrations"` should be sufficient.

### How to reproduce (as minimally and precisely as possible)
Just exclude a file with posix path noatation on windows, and it won't be excluded.

### Anthing else we need to know?
This can be fixed by using `os.path.normpath` in the following line.
https://github.com/econchick/interrogate/blob/624dc095d44aeaf34c73f29151111a14588eb129/src/interrogate/coverage.py#L131-L136

```python 
            maybe_excluded_dir = any(
                [f.startswith(os.path.normpath(exc)) for exc in self.excluded]
            )
```

Also `maybe_excluded_file ` seams to be redundant since `some_str.startswith(some_str) == some_str in (some_str,)`

```python
In [1]: file_path = "/home/user/foo"

In [2]: exclude = (file_path, )

In [3]: any(file_path.startswith(exc) for exc in exclude)
Out[3]: True

In [4]: file_path in exclude
Out[4]: True
```

**Comment by econchick** [comment]
ah! great catch @s-weigand - thanks for filing this. I'll try to get to addressing it over the weekend.

**Comment by oriash93** [comment]
@econchick Is it possible for me to take up on that?
Thanks

**Comment by econchick** [comment]
Hey @oriash93 - if you’d like! I’d certainly welcome a PR.
