### ISSUE TITLE
[Feature Request] Allow glob pattern for exclude paths

### ISSUE THREAD

**Issue by s-weigand** [econchick/interrogate#59]
### Describe the feature you'd like

Atm it is not possible to exclude files by a pattern, i.e. `*tests*`.
Which means that each path needs to be added explicitly to the exclude list.
While this might be ok for very small projects, it gets quite nasty for bigger projects.

### Is your feature request related to a problem?

If you have a project where the tests are part of the package and its subpackages, i.e.:
```
project/
    tests/
     sub-package1/
         tests/
     sub-package2/
         tests/
```
You would need to add `project/tests`, `project/ sub-package1/tests` and `project/ sub-package2/tests` to be excluded, if you want to exclude all tests.

### Additional context

The desired behaviour could be quite easily achieved by checking the path to exclude with [fnmatch](https://docs.python.org/3.8/library/fnmatch.html#module-fnmatch), this would at the same time solve #51 and could be included in #56 .

```python
In [1]: from fnmatch import fnmatch

In [2]: test_paths = ["/home/project/tests", "/home/project/tests/test_file", r"C:\project\tests", r"C:\project\tests\test_file"]

In [3]: [fnmatch(test_path, "*tests") for test_path in test_paths]
Out[3]: [True, False, True, False]

In [4]: [fnmatch(test_path, "*tests*") for test_path in test_paths]
Out[4]: [True, True, True, True]

In [5]: [fnmatch(test_path, "*/tests*") for test_path in test_paths]
Out[5]: [True, True, True, True]

In [6]: [fnmatch(test_path, "/home/project/tests*") for test_path in test_paths]
Out[6]: [True, True, False, False]

In [7]: fnmatch(r"project\tests\test_file.py", "project/tests")
Out[7]: False

In [8]: fnmatch(r"project\tests\test_file.py", "project/tests*")
Out[8]: True

In [9]: fnmatch(r"project\tests", "project/tests")
Out[9]: True
```

**Comment by econchick** [comment]
I agree - we already have `--ignore-regex`  & `--whitelist-regex` for code-based regexes. Would be good to have two similar flags for paths.

This fall is a bit busy for me - if you (or any lurkers) wish to take this on, I'd be very happy to take a pull request. Otherwise, it may be a little while (a week or two) before I can get to this.

**Comment by s-weigand** [comment]
IMHO for the case of file paths, `--exclude` should be enough.
If people just want to ignore specific files in a folder, they can just use a glob pattern with a higher specificity.
I.e. you want to exclude the tests themselves, but enforce that you fixtures got docstring
```
project/
    tests/
     sub-package1/
         tests/
             conftest.py
             test_func1.py
             test_func2.py

```
With the above project structure you would run
`interrogate -e "project/sub-package1/tests/test_*" project`
