### ISSUE TITLE
Split out the `--ignore-property-decorators` to allow ignore setter only

### ISSUE THREAD

**Issue by chrisbeardy** [econchick/interrogate#68]
### Describe the feature you'd like
Currently the `-P, --ignore-property-decorators` option ignores methods with property setter/getter decorators. 
I (and potentially others) often just document the getter as IDEs like PyCharm will use the getter documentation for the setter too. This prevents the need to duplicate docstrings across the getter and setter. 

It would be great if there was an option that allowed to just ignore the the setter only on a property.

**Comment by econchick** [comment]
Hey @chrisbeardy - sorry for the delay! Thank you for the suggestion. I merged in #74 that added `-S`/`--ignore-setters` that will be released in `1.4.0` (hopefully uploaded later tonight).
