### ISSUE TITLE
Document what level of `verbose` `-vv` corresponds to

### ISSUE THREAD

**Issue by RoyalTS** [econchick/interrogate#83]
I take it the `-v` option corresponds to `verbose=1`. Does `-vv` correspond to `verbose=2`?

**Comment by econchick** [comment]
hey @RoyalTS - just to be clear, you are requesting better docs around `verbose` when setting it in config, e.g. `pyproject.toml`?

**Comment by RoyalTS** [comment]
Yeah, sorry, should have been clearer. I'm asking for the correspondence between the command-line arguments and the settings.

**Comment by econchick** [comment]
Gotcha! So sorry for the confusion, I’ll definitely update the docs for better clarity.

And yeah, you have it correct: in config, if you want no verbosity, then it’s verbose = 0. If you want the equivalent of -v, then it’s verbose = 1. And -vv is verbose = 2.

**Comment by econchick** [comment]
(finally) addressed this in #89 - sorry for the delay, thanks!
