### ISSUE TITLE
Add --skip-covered flag to disable reporting covered files

### ISSUE THREAD

**Issue by RobertCraigie** [econchick/interrogate#85]
### Describe the feature you'd like

Interrogate's output can get very verbose which is very useful, however sometimes it would also be useful to ignore any files that are 100% covered to focus on the files that need docstrings added, I suggest adding a `--skip-covered` flag to disable reporting of such files.

### Is your feature request related to a problem?

No

### Your Environment

- `interrogate` version(s) (`interrogate --version`: version 1.4.0
- Operating System(s): MacOS
- Python version(s): 3.9

### Additional context

Coverage.py supports [skipping covered files](https://coverage.readthedocs.io/en/coverage-5.5/cmd.html#reporting)

**Comment by econchick** [comment]
Thanks for the good idea! I'll try to add this functionality in the next week or so for the 1.5.0 release.

**Comment by econchick** [comment]
FYI I've added this (as `--omit-covered-files`) and will be included in the 1.5.0 release. Not sure when I'll be able to make the release as I want to get a few more things in before, but I'll update this ticket once I do!

**Comment by econchick** [comment]
Update: 1.5.0 has been released! Let me know what you think / if you have any issues!

**Comment by RobertCraigie** [comment]
Thank you!
