### ISSUE TITLE
Support for multiple styles for the interrogate badge

### ISSUE THREAD

**Issue by astrogewgaw** [econchick/interrogate#86]
<div align="justify">

Is it possible for the **interrogate** badge to support all the styles supported by [**Shields.io**](https://shields.io/), namely: _plastic_, _flat_, _flat-square_ and _for-the-badge_? I wish to use the interrogate badge in my READMEs, but since I prefer the _for-the-badge_ style, it ends up looking like the odd one out 😅 . I am using **interrogate** `v1.3.2`, with Python v3.8 and Ubuntu 20.04.

</div>

**Comment by econchick** [comment]
Hey @astrogewgaw - it's not possible right now, but I like the idea and will try to add support for different styles in the next week or so for the 1.5.0 release. Thanks!

**Comment by astrogewgaw** [comment]
No worries @econchick 😁 ! Glad to see that this is (hopefully 🤞🏾) going to make the 1.5.0 release. Thanks for both responding so quickly and for making this awesome project in the first place 😄 !

**Comment by econchick** [comment]
Hey @astrogewgaw ! I finally added a `--badge-style` flag to `interrogate`, and is in the newly-released 1.5.0 version! [Check it out](https://interrogate.readthedocs.io/en/latest/#badge-options) and tell me what you think!
