### ISSUE TITLE
Option to ignore overloaded functions

### ISSUE THREAD

**Issue by ErwinJunge** [econchick/interrogate#97]
### Describe the feature you'd like
When decorating functions with `@typing.overload`, the stubs are marked as not covered when they don't have their own docstring. My suggestion is to add an option to ignore those stubs.

### Is your feature request related to a problem?
We have overloaded functions in our codebase that we want to start using this package in and we only document the actual implementation and not the stubs.

### Your Environment
- `interrogate` version(s) (`interrogate --version`: 1.5.0
- Operating System(s): linux
- Python version(s): 3.6-3.10

### Additional context
PR incoming.

**Comment by amin-nejad** [comment]
Another option is to ignore `flake8` rule **D418** (doesn't allow docstrings for overloads) and just give the overloaded functions/methods docstrings. But agree it would be good to have the option to have interrogate ignore them for this purpose.
